language: node_js
node_js:
  - lts/dubnium

jobs:
  include:
    - stage: test
      name: 'Testing and linting'
      script:
        - yarn lint
        - yarn test
    - stage: build
      name: 'Building and deploying to NPM'
      script: yarn build
      deploy:
        - provider: npm
          if: branch != master
          edge: true
          email: $NPM_EMAIL
          api_token: $NPM_TOKEN
          dry_run: true
        - provider: script
          edge: true
          script: npx semantic-release
          on:
            branch: master
